[connections]
[connections.dummy_1]
account = "dummy"
user = "dummy"
password = "dummy"
warehouse = "dummy"
role = "dummy"


[connections.dummy_2]
account = "dummy"
user = "dummy"
password = "dummy"
warehouse = "dummy"
role = "dummy"


