name: Continuous Deployment Of Docker Image to Snowpark Container Services

on: [push]  

# Set Environmental Variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_LOGIN_NAME: ${{secrets.DOCKER_LOGIN_NAME}}
  SNOWFLAKE_CONNECTIONS_DUMMY_ACCOUNT: ${{secrets.spc_account}}
  SNOWFLAKE_CONNECTIONS_DUMMY_USER: ${{secrets.spc_USER}}
  SNOWFLAKE_CONNECTIONS_DUMMY_PASSWORD: ${{secrets.spc_PASSWORD}}

   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name : Docker Login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Run a command 
      run: echo "User=$DOCKER_USER"
    - name: Docker build image
      run: docker build --rm --platform linux/amd64 -t dbt_app  -f ./Dockerfile .
    - name: list images
      run: docker images
    
    - uses: Snowflake-Labs/snowflake-cli-action@v1
      with:
        cli-version: "latest"
        default-config-file-path: "config.toml"
    
    # Use the CLI
    - name: Test version
      run: snow --version
    
    - name: Test Connection Snowpark Container Services
      env:
        SNOWFLAKE_CONNECTIONS_DUMMY_ACCOUNT: ${{secrets.spc_account}}
        SNOWFLAKE_CONNECTIONS_DUMMY_USER: ${{secrets.spc_USER}}
        SNOWFLAKE_CONNECTIONS_DUMMY_PASSWORD: ${{secrets.spc_PASSWORD}}
        SNOWFLAKE_CONNECTIONS_DUMMY_ROLE: doc_ai_role
        SNOWFLAKE_CONNECTIONS_DUMMY_WAREHOUSE: Compute_wh_v1
      run : snow connection test --connection Dummy

    - name: test snowcli
      env:
        SNOWFLAKE_CONNECTIONS_DUMMY_ACCOUNT: ${{secrets.ai_aCCOUNT}}
        SNOWFLAKE_CONNECTIONS_DUMMY_USER: ${{secrets.ai_USER}}
        SNOWFLAKE_CONNECTIONS_DUMMY_PASSWORD: ${{secrets.ai_PASSWORD}}
        SNOWFLAKE_CONNECTIONS_DUMMY_ROLE: accountadmin
        SNOWFLAKE_CONNECTIONS_DUMMY_WAREHOUSE: Compute_wh
        SNOWFLAKE_CONNECTIONS_DUMMY_DATABASE: doc_ai_db
      run: snow sql -q "select 42+1 as val;" --connection Dummy
    
    - name: start snowflake_tasks
      env:
        SNOWFLAKE_CONNECTIONS_DUMMY_ACCOUNT: ${{secrets.ai_aCCOUNT}}
        SNOWFLAKE_CONNECTIONS_DUMMY_USER: ${{secrets.ai_USER}}
        SNOWFLAKE_CONNECTIONS_DUMMY_PASSWORD: ${{secrets.ai_PASSWORD}}
        SNOWFLAKE_CONNECTIONS_DUMMY_ROLE: accountadmin
        SNOWFLAKE_CONNECTIONS_DUMMY_WAREHOUSE: Compute_wh
        SNOWFLAKE_CONNECTIONS_DUMMY_DATABASE: doc_ai_db
        SNOWFLAKE_CONNECTIONS_DUMMY_SCHEMA: doc_ai_schema
      run: snow sql -q "ALTER TASK LOAD_NEW_FILE_DATA RESUME; ALTER TASK REFRESH_STAGE RESUME;" --connection Dummy
    
    - name: dbt_repository
      env:
        SNOWFLAKE_CONNECTIONS_DUMMY_ACCOUNT: ${{secrets.spc_account}}
        SNOWFLAKE_CONNECTIONS_DUMMY_USER: ${{secrets.spc_USER}}
        SNOWFLAKE_CONNECTIONS_DUMMY_PASSWORD: ${{secrets.spc_PASSWORD}}
        SNOWFLAKE_CONNECTIONS_DUMMY_ROLE: doc_ai_role
        SNOWFLAKE_CONNECTIONS_DUMMY_WAREHOUSE: Compute_wh_v1
        SNOWFLAKE_CONNECTIONS_DUMMY_DATABASE: doc_ai_db
        SNOWFLAKE_CONNECTIONS_DUMMY_SCHEMA: doc_ai_schema
      run: |
        snow spcs image-repository url dbt_repository --connection Dummy
        docker tag dbt_app hiiwhnq-nc74811.registry.snowflakecomputing.com/doc_ai_db/doc_ai_schema/dbt_repository/dbt_app:latest
        docker images
        snow spcs image-registry login --connection Dummy
        docker push hiiwhnq-nc74811.registry.snowflakecomputing.com/doc_ai_db/doc_ai_schema/dbt_repository/dbt_app:latest 
        snow spcs service create dbt_service --compute-pool dbt_compute --spec-path container-services-dbt/app/spec.yml --eai-name 'test_DBT_SNOWFLAKE_EGRESS_ACCESSS_INTEGRATION' --if-not-exists --connection Dummy
    
    - name: Sleep for 120 seconds. Allow Service to Start and Create Endpoint
      run: sleep 120s
      shell: bash
    
    - name :  Get service details 
      env:
        SNOWFLAKE_CONNECTIONS_DUMMY_ACCOUNT: ${{secrets.spc_account}}
        SNOWFLAKE_CONNECTIONS_DUMMY_USER: ${{secrets.spc_USER}}
        SNOWFLAKE_CONNECTIONS_DUMMY_PASSWORD: ${{secrets.spc_PASSWORD}}
        SNOWFLAKE_CONNECTIONS_DUMMY_ROLE: doc_ai_role 
        SNOWFLAKE_CONNECTIONS_DUMMY_WAREHOUSE: Compute_wh_v1
        SNOWFLAKE_CONNECTIONS_DUMMY_DATABASE: doc_ai_db
        SNOWFLAKE_CONNECTIONS_DUMMY_SCHEMA: doc_ai_schema
      run : |
        snow spcs service status dbt_service --connection Dummy

    